name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Action Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
           push: false
           context: .
           file: ./Dockerfile
           registry: ghcr.io
           tags: |
            ghcr.io/aolle/antora-site-action:latest
      - uses: GoogleCloudPlatform/release-please-action@v3.7.12
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
